[package]
name = "dcs-get"
version = "0.1.0"
authors = ["David Richardson <david@tankski.co.uk>"]

[dependencies]
clippy = "*"
docopt = "0.6.78"
rustc-serialize = "0.3.18"
termion = { git = "https://github.com/Ticki/termion.git" }